version: "3"
services:
  react-app:
    build: ./client
    image: react-app-image
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern-app
  api-server:
    build: ./server
    image: api-server-image
    ports:
      - "5000:5000"
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local